// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: secrets/secrets.proto

package secretspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretService_GetSecret_FullMethodName = "/secrets.SecretService/GetSecret"
	SecretService_GetAstro_FullMethodName  = "/secrets.SecretService/GetAstro"
	SecretService_JwtLab_FullMethodName    = "/secrets.SecretService/JwtLab"
	SecretService_CurlMix_FullMethodName   = "/secrets.SecretService/CurlMix"
	SecretService_Cdn_FullMethodName       = "/secrets.SecretService/Cdn"
	SecretService_Health_FullMethodName    = "/secrets.SecretService/Health"
)

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretServiceClient interface {
	GetSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error)
	GetAstro(ctx context.Context, in *AstroRequest, opts ...grpc.CallOption) (*AstroResponse, error)
	JwtLab(ctx context.Context, in *JwtLabRequest, opts ...grpc.CallOption) (*JwtLabResponse, error)
	CurlMix(ctx context.Context, in *CurlMixRequest, opts ...grpc.CallOption) (*CurlMixResponse, error)
	Cdn(ctx context.Context, in *CdnRequest, opts ...grpc.CallOption) (*CdnResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type secretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretServiceClient(cc grpc.ClientConnInterface) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, SecretService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) GetAstro(ctx context.Context, in *AstroRequest, opts ...grpc.CallOption) (*AstroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AstroResponse)
	err := c.cc.Invoke(ctx, SecretService_GetAstro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) JwtLab(ctx context.Context, in *JwtLabRequest, opts ...grpc.CallOption) (*JwtLabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JwtLabResponse)
	err := c.cc.Invoke(ctx, SecretService_JwtLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) CurlMix(ctx context.Context, in *CurlMixRequest, opts ...grpc.CallOption) (*CurlMixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurlMixResponse)
	err := c.cc.Invoke(ctx, SecretService_CurlMix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) Cdn(ctx context.Context, in *CdnRequest, opts ...grpc.CallOption) (*CdnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CdnResponse)
	err := c.cc.Invoke(ctx, SecretService_Cdn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SecretService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
// All implementations must embed UnimplementedSecretServiceServer
// for forward compatibility.
type SecretServiceServer interface {
	GetSecret(context.Context, *SecretRequest) (*SecretResponse, error)
	GetAstro(context.Context, *AstroRequest) (*AstroResponse, error)
	JwtLab(context.Context, *JwtLabRequest) (*JwtLabResponse, error)
	CurlMix(context.Context, *CurlMixRequest) (*CurlMixResponse, error)
	Cdn(context.Context, *CdnRequest) (*CdnResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSecretServiceServer()
}

// UnimplementedSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretServiceServer struct{}

func (UnimplementedSecretServiceServer) GetSecret(context.Context, *SecretRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretServiceServer) GetAstro(context.Context, *AstroRequest) (*AstroResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAstro not implemented")
}
func (UnimplementedSecretServiceServer) JwtLab(context.Context, *JwtLabRequest) (*JwtLabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JwtLab not implemented")
}
func (UnimplementedSecretServiceServer) CurlMix(context.Context, *CurlMixRequest) (*CurlMixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurlMix not implemented")
}
func (UnimplementedSecretServiceServer) Cdn(context.Context, *CdnRequest) (*CdnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cdn not implemented")
}
func (UnimplementedSecretServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSecretServiceServer) mustEmbedUnimplementedSecretServiceServer() {}
func (UnimplementedSecretServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretServiceServer will
// result in compilation errors.
type UnsafeSecretServiceServer interface {
	mustEmbedUnimplementedSecretServiceServer()
}

func RegisterSecretServiceServer(s grpc.ServiceRegistrar, srv SecretServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretService_ServiceDesc, srv)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_GetAstro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AstroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetAstro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_GetAstro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetAstro(ctx, req.(*AstroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_JwtLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).JwtLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_JwtLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).JwtLab(ctx, req.(*JwtLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_CurlMix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurlMixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).CurlMix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_CurlMix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).CurlMix(ctx, req.(*CurlMixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_Cdn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CdnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).Cdn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_Cdn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).Cdn(ctx, req.(*CdnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretService_ServiceDesc is the grpc.ServiceDesc for SecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secrets.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "GetAstro",
			Handler:    _SecretService_GetAstro_Handler,
		},
		{
			MethodName: "JwtLab",
			Handler:    _SecretService_JwtLab_Handler,
		},
		{
			MethodName: "CurlMix",
			Handler:    _SecretService_CurlMix_Handler,
		},
		{
			MethodName: "Cdn",
			Handler:    _SecretService_Cdn_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SecretService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secrets/secrets.proto",
}
