// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Minimal nested structure — small enough that protoscope
// will inline the sub-messages, producing position-dependent indentation.
type FacetValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FacetValue_Numeric
	//	*FacetValue_Text
	Value         isFacetValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetValue) Reset() {
	*x = FacetValue{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetValue) ProtoMessage() {}

func (x *FacetValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetValue.ProtoReflect.Descriptor instead.
func (*FacetValue) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *FacetValue) GetValue() isFacetValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FacetValue) GetNumeric() float64 {
	if x != nil {
		if x, ok := x.Value.(*FacetValue_Numeric); ok {
			return x.Numeric
		}
	}
	return 0
}

func (x *FacetValue) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*FacetValue_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isFacetValue_Value interface {
	isFacetValue_Value()
}

type FacetValue_Numeric struct {
	Numeric float64 `protobuf:"fixed64,2,opt,name=numeric,proto3,oneof"`
}

type FacetValue_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

func (*FacetValue_Numeric) isFacetValue_Value() {}

func (*FacetValue_Text) isFacetValue_Value() {}

type FacetEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *FacetValue            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetEntry) Reset() {
	*x = FacetEntry{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetEntry) ProtoMessage() {}

func (x *FacetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetEntry.ProtoReflect.Descriptor instead.
func (*FacetEntry) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *FacetEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FacetEntry) GetData() *FacetValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type FacetBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FacetEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetBucket) Reset() {
	*x = FacetBucket{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetBucket) ProtoMessage() {}

func (x *FacetBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetBucket.ProtoReflect.Descriptor instead.
func (*FacetBucket) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *FacetBucket) GetEntries() []*FacetEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FacetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pricing       *FacetBucket           `protobuf:"bytes,2,opt,name=pricing,proto3" json:"pricing,omitempty"`
	Availability  *FacetBucket           `protobuf:"bytes,3,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetInfo) Reset() {
	*x = FacetInfo{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetInfo) ProtoMessage() {}

func (x *FacetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetInfo.ProtoReflect.Descriptor instead.
func (*FacetInfo) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *FacetInfo) GetPricing() *FacetBucket {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *FacetInfo) GetAvailability() *FacetBucket {
	if x != nil {
		return x.Availability
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	HitsJson      string                 `protobuf:"bytes,4,opt,name=hits_json,json=hitsJson,proto3" json:"hits_json,omitempty"`
	Total         int32                  `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	Facets        *FacetInfo             `protobuf:"bytes,9,opt,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResponse) GetHitsJson() string {
	if x != nil {
		return x.HitsJson
	}
	return ""
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetFacets() *FacetInfo {
	if x != nil {
		return x.Facets
	}
	return nil
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"G\n" +
	"\n" +
	"FacetValue\x12\x1a\n" +
	"\anumeric\x18\x02 \x01(\x01H\x00R\anumeric\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04textB\a\n" +
	"\x05value\"H\n" +
	"\n" +
	"FacetEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.search.FacetValueR\x04data\";\n" +
	"\vFacetBucket\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.search.FacetEntryR\aentries\"s\n" +
	"\tFacetInfo\x12-\n" +
	"\apricing\x18\x02 \x01(\v2\x13.search.FacetBucketR\apricing\x127\n" +
	"\favailability\x18\x03 \x01(\v2\x13.search.FacetBucketR\favailability\"\x84\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x1b\n" +
	"\thits_json\x18\x04 \x01(\tR\bhitsJson\x12\x14\n" +
	"\x05total\x18\b \x01(\x05R\x05total\x12)\n" +
	"\x06facets\x18\t \x01(\v2\x11.search.FacetInfoR\x06facets2H\n" +
	"\rSearchService\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseB\fZ\n" +
	"./searchpbb\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: search.SearchRequest
	(*FacetValue)(nil),     // 1: search.FacetValue
	(*FacetEntry)(nil),     // 2: search.FacetEntry
	(*FacetBucket)(nil),    // 3: search.FacetBucket
	(*FacetInfo)(nil),      // 4: search.FacetInfo
	(*SearchResponse)(nil), // 5: search.SearchResponse
}
var file_proto_search_proto_depIdxs = []int32{
	1, // 0: search.FacetEntry.data:type_name -> search.FacetValue
	2, // 1: search.FacetBucket.entries:type_name -> search.FacetEntry
	3, // 2: search.FacetInfo.pricing:type_name -> search.FacetBucket
	3, // 3: search.FacetInfo.availability:type_name -> search.FacetBucket
	4, // 4: search.SearchResponse.facets:type_name -> search.FacetInfo
	0, // 5: search.SearchService.Search:input_type -> search.SearchRequest
	5, // 6: search.SearchService.Search:output_type -> search.SearchResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	file_proto_search_proto_msgTypes[1].OneofWrappers = []any{
		(*FacetValue_Numeric)(nil),
		(*FacetValue_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
