#==============================================================================
# GOLANGCI-LINT CONFIGURATION
#==============================================================================
# This configuration file defines the static analysis rules for all Go projects
# in this repository. It's optimized for use with reviewdog in GitHub Actions
# to provide inline PR comments.
#
# Reference: https://golangci-lint.run/usage/configuration/
#==============================================================================

version: "2"

output:
  show-stats: true
  sort-order:
    - file
    - linter

