// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: svc/v1/product.proto

package svcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InStock       bool                   `protobuf:"varint,6,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Categories    []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Details       *ProductDetails        `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_svc_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_svc_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDetails() *ProductDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type ProductDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer   string                 `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model          string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	WarrantyMonths int32                  `protobuf:"varint,3,opt,name=warranty_months,json=warrantyMonths,proto3" json:"warranty_months,omitempty"`
	Weight         float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions     map[string]float64     `protobuf:"bytes,5,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductDetails) Reset() {
	*x = ProductDetails{}
	mi := &file_svc_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetails) ProtoMessage() {}

func (x *ProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetails.ProtoReflect.Descriptor instead.
func (*ProductDetails) Descriptor() ([]byte, []int) {
	return file_svc_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductDetails) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ProductDetails) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProductDetails) GetWarrantyMonths() int32 {
	if x != nil {
		return x.WarrantyMonths
	}
	return 0
}

func (x *ProductDetails) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductDetails) GetDimensions() map[string]float64 {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

var File_svc_v1_product_proto protoreflect.FileDescriptor

const file_svc_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x14svc/v1/product.proto\x12\x06svc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x19\n" +
	"\bin_stock\x18\x06 \x01(\bR\ainStock\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12?\n" +
	"\n" +
	"attributes\x18\b \x03(\v2\x1f.svc.v1.Product.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\adetails\x18\n" +
	" \x01(\v2\x16.svc.v1.ProductDetailsR\adetails\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x02\n" +
	"\x0eProductDetails\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12'\n" +
	"\x0fwarranty_months\x18\x03 \x01(\x05R\x0ewarrantyMonths\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12F\n" +
	"\n" +
	"dimensions\x18\x05 \x03(\v2&.svc.v1.ProductDetails.DimensionsEntryR\n" +
	"dimensions\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01BHZFgithub.com/keploy/samples-go/grpc-apps/multi-proto/protos/svc/v1;svcv1b\x06proto3"

var (
	file_svc_v1_product_proto_rawDescOnce sync.Once
	file_svc_v1_product_proto_rawDescData []byte
)

func file_svc_v1_product_proto_rawDescGZIP() []byte {
	file_svc_v1_product_proto_rawDescOnce.Do(func() {
		file_svc_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_v1_product_proto_rawDesc), len(file_svc_v1_product_proto_rawDesc)))
	})
	return file_svc_v1_product_proto_rawDescData
}

var file_svc_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_svc_v1_product_proto_goTypes = []any{
	(*Product)(nil),               // 0: svc.v1.Product
	(*ProductDetails)(nil),        // 1: svc.v1.ProductDetails
	nil,                           // 2: svc.v1.Product.AttributesEntry
	nil,                           // 3: svc.v1.ProductDetails.DimensionsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_svc_v1_product_proto_depIdxs = []int32{
	2, // 0: svc.v1.Product.attributes:type_name -> svc.v1.Product.AttributesEntry
	4, // 1: svc.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: svc.v1.Product.details:type_name -> svc.v1.ProductDetails
	3, // 3: svc.v1.ProductDetails.dimensions:type_name -> svc.v1.ProductDetails.DimensionsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_svc_v1_product_proto_init() }
func file_svc_v1_product_proto_init() {
	if File_svc_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_v1_product_proto_rawDesc), len(file_svc_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_v1_product_proto_goTypes,
		DependencyIndexes: file_svc_v1_product_proto_depIdxs,
		MessageInfos:      file_svc_v1_product_proto_msgTypes,
	}.Build()
	File_svc_v1_product_proto = out.File
	file_svc_v1_product_proto_goTypes = nil
	file_svc_v1_product_proto_depIdxs = nil
}
