// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: svc/v1/service.proto

package svcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	GetSimpleData(ctx context.Context, in *SimpleDataRequest, opts ...grpc.CallOption) (*SimpleDataResponse, error)
	GetComplexData(ctx context.Context, in *ComplexDataRequest, opts ...grpc.CallOption) (*ComplexDataResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetSimpleData(ctx context.Context, in *SimpleDataRequest, opts ...grpc.CallOption) (*SimpleDataResponse, error) {
	out := new(SimpleDataResponse)
	err := c.cc.Invoke(ctx, "/svc.v1.DataService/GetSimpleData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetComplexData(ctx context.Context, in *ComplexDataRequest, opts ...grpc.CallOption) (*ComplexDataResponse, error) {
	out := new(ComplexDataResponse)
	err := c.cc.Invoke(ctx, "/svc.v1.DataService/GetComplexData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility
type DataServiceServer interface {
	GetSimpleData(context.Context, *SimpleDataRequest) (*SimpleDataResponse, error)
	GetComplexData(context.Context, *ComplexDataRequest) (*ComplexDataResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (UnimplementedDataServiceServer) GetSimpleData(context.Context, *SimpleDataRequest) (*SimpleDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimpleData not implemented")
}
func (UnimplementedDataServiceServer) GetComplexData(context.Context, *ComplexDataRequest) (*ComplexDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComplexData not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_GetSimpleData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetSimpleData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.v1.DataService/GetSimpleData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetSimpleData(ctx, req.(*SimpleDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetComplexData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComplexDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetComplexData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.v1.DataService/GetComplexData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetComplexData(ctx, req.(*ComplexDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSimpleData",
			Handler:    _DataService_GetSimpleData_Handler,
		},
		{
			MethodName: "GetComplexData",
			Handler:    _DataService_GetComplexData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/v1/service.proto",
}
