// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: svc/v1/service.proto

package svcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleDataRequest) Reset() {
	*x = SimpleDataRequest{}
	mi := &file_svc_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleDataRequest) ProtoMessage() {}

func (x *SimpleDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleDataRequest.ProtoReflect.Descriptor instead.
func (*SimpleDataRequest) Descriptor() ([]byte, []int) {
	return file_svc_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SimpleDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Items         []string               `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleDataResponse) Reset() {
	*x = SimpleDataResponse{}
	mi := &file_svc_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleDataResponse) ProtoMessage() {}

func (x *SimpleDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleDataResponse.ProtoReflect.Descriptor instead.
func (*SimpleDataResponse) Descriptor() ([]byte, []int) {
	return file_svc_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SimpleDataResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SimpleDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimpleDataResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SimpleDataResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SimpleDataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SimpleDataResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ComplexDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexDataRequest) Reset() {
	*x = ComplexDataRequest{}
	mi := &file_svc_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexDataRequest) ProtoMessage() {}

func (x *ComplexDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexDataRequest.ProtoReflect.Descriptor instead.
func (*ComplexDataRequest) Descriptor() ([]byte, []int) {
	return file_svc_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexDataRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ComplexDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ComplexDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Products      []*Product             `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	Statistics    map[string]int32       `protobuf:"bytes,6,rep,name=statistics,proto3" json:"statistics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexDataResponse) Reset() {
	*x = ComplexDataResponse{}
	mi := &file_svc_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexDataResponse) ProtoMessage() {}

func (x *ComplexDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexDataResponse.ProtoReflect.Descriptor instead.
func (*ComplexDataResponse) Descriptor() ([]byte, []int) {
	return file_svc_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ComplexDataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComplexDataResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ComplexDataResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ComplexDataResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ComplexDataResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ComplexDataResponse) GetStatistics() map[string]int32 {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *ComplexDataResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *ComplexDataResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResponseMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProcessingTimeMs float64                `protobuf:"fixed64,2,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Tags             map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_svc_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_svc_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_svc_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMetadata) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *ResponseMetadata) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ResponseMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_svc_v1_service_proto protoreflect.FileDescriptor

const file_svc_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14svc/v1/service.proto\x12\x06svc.v1\x1a\x11svc/v1/user.proto\x1a\x14svc/v1/product.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11SimpleDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc5\x02\n" +
	"\x12SimpleDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x14\n" +
	"\x05items\x18\x05 \x03(\tR\x05items\x12D\n" +
	"\bmetadata\x18\x06 \x03(\v2(.svc.v1.SimpleDataResponse.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x12ComplexDataRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xbb\x03\n" +
	"\x13ComplexDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\"\n" +
	"\x05users\x18\x04 \x03(\v2\f.svc.v1.UserR\x05users\x12+\n" +
	"\bproducts\x18\x05 \x03(\v2\x0f.svc.v1.ProductR\bproducts\x12K\n" +
	"\n" +
	"statistics\x18\x06 \x03(\v2+.svc.v1.ComplexDataResponse.StatisticsEntryR\n" +
	"statistics\x12=\n" +
	"\fprocessed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x124\n" +
	"\bmetadata\x18\b \x01(\v2\x18.svc.v1.ResponseMetadataR\bmetadata\x1a=\n" +
	"\x0fStatisticsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf7\x01\n" +
	"\x10ResponseMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x12processing_time_ms\x18\x02 \x01(\x01R\x10processingTimeMs\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x126\n" +
	"\x04tags\x18\x04 \x03(\v2\".svc.v1.ResponseMetadata.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa0\x01\n" +
	"\vDataService\x12F\n" +
	"\rGetSimpleData\x12\x19.svc.v1.SimpleDataRequest\x1a\x1a.svc.v1.SimpleDataResponse\x12I\n" +
	"\x0eGetComplexData\x12\x1a.svc.v1.ComplexDataRequest\x1a\x1b.svc.v1.ComplexDataResponseBHZFgithub.com/keploy/samples-go/grpc-apps/multi-proto/protos/svc/v1;svcv1b\x06proto3"

var (
	file_svc_v1_service_proto_rawDescOnce sync.Once
	file_svc_v1_service_proto_rawDescData []byte
)

func file_svc_v1_service_proto_rawDescGZIP() []byte {
	file_svc_v1_service_proto_rawDescOnce.Do(func() {
		file_svc_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_v1_service_proto_rawDesc), len(file_svc_v1_service_proto_rawDesc)))
	})
	return file_svc_v1_service_proto_rawDescData
}

var file_svc_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_svc_v1_service_proto_goTypes = []any{
	(*SimpleDataRequest)(nil),     // 0: svc.v1.SimpleDataRequest
	(*SimpleDataResponse)(nil),    // 1: svc.v1.SimpleDataResponse
	(*ComplexDataRequest)(nil),    // 2: svc.v1.ComplexDataRequest
	(*ComplexDataResponse)(nil),   // 3: svc.v1.ComplexDataResponse
	(*ResponseMetadata)(nil),      // 4: svc.v1.ResponseMetadata
	nil,                           // 5: svc.v1.SimpleDataResponse.MetadataEntry
	nil,                           // 6: svc.v1.ComplexDataResponse.StatisticsEntry
	nil,                           // 7: svc.v1.ResponseMetadata.TagsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*User)(nil),                  // 9: svc.v1.User
	(*Product)(nil),               // 10: svc.v1.Product
}
var file_svc_v1_service_proto_depIdxs = []int32{
	5,  // 0: svc.v1.SimpleDataResponse.metadata:type_name -> svc.v1.SimpleDataResponse.MetadataEntry
	8,  // 1: svc.v1.SimpleDataResponse.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 2: svc.v1.ComplexDataResponse.users:type_name -> svc.v1.User
	10, // 3: svc.v1.ComplexDataResponse.products:type_name -> svc.v1.Product
	6,  // 4: svc.v1.ComplexDataResponse.statistics:type_name -> svc.v1.ComplexDataResponse.StatisticsEntry
	8,  // 5: svc.v1.ComplexDataResponse.processed_at:type_name -> google.protobuf.Timestamp
	4,  // 6: svc.v1.ComplexDataResponse.metadata:type_name -> svc.v1.ResponseMetadata
	7,  // 7: svc.v1.ResponseMetadata.tags:type_name -> svc.v1.ResponseMetadata.TagsEntry
	0,  // 8: svc.v1.DataService.GetSimpleData:input_type -> svc.v1.SimpleDataRequest
	2,  // 9: svc.v1.DataService.GetComplexData:input_type -> svc.v1.ComplexDataRequest
	1,  // 10: svc.v1.DataService.GetSimpleData:output_type -> svc.v1.SimpleDataResponse
	3,  // 11: svc.v1.DataService.GetComplexData:output_type -> svc.v1.ComplexDataResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_svc_v1_service_proto_init() }
func file_svc_v1_service_proto_init() {
	if File_svc_v1_service_proto != nil {
		return
	}
	file_svc_v1_user_proto_init()
	file_svc_v1_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_v1_service_proto_rawDesc), len(file_svc_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_v1_service_proto_goTypes,
		DependencyIndexes: file_svc_v1_service_proto_depIdxs,
		MessageInfos:      file_svc_v1_service_proto_msgTypes,
	}.Build()
	File_svc_v1_service_proto = out.File
	file_svc_v1_service_proto_goTypes = nil
	file_svc_v1_service_proto_depIdxs = nil
}
