// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: api/proto/loadtest.proto

package loadtestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Segment       string                 `protobuf:"bytes,4,opt,name=segment,proto3" json:"segment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_api_proto_loadtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Customer) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *Customer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Segment       string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCustomerRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

type GetCustomerSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerSummaryRequest) Reset() {
	*x = GetCustomerSummaryRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerSummaryRequest) ProtoMessage() {}

func (x *GetCustomerSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerSummaryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CustomerSummary struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Customer               *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	OrdersCount            int32                  `protobuf:"varint,2,opt,name=orders_count,json=ordersCount,proto3" json:"orders_count,omitempty"`
	LifetimeValueCents     int64                  `protobuf:"varint,3,opt,name=lifetime_value_cents,json=lifetimeValueCents,proto3" json:"lifetime_value_cents,omitempty"`
	AverageOrderValueCents int64                  `protobuf:"varint,4,opt,name=average_order_value_cents,json=averageOrderValueCents,proto3" json:"average_order_value_cents,omitempty"`
	FavoriteCategory       string                 `protobuf:"bytes,5,opt,name=favorite_category,json=favoriteCategory,proto3" json:"favorite_category,omitempty"`
	LastOrderAt            string                 `protobuf:"bytes,6,opt,name=last_order_at,json=lastOrderAt,proto3" json:"last_order_at,omitempty"` // RFC3339, empty if no orders
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CustomerSummary) Reset() {
	*x = CustomerSummary{}
	mi := &file_api_proto_loadtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSummary) ProtoMessage() {}

func (x *CustomerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSummary.ProtoReflect.Descriptor instead.
func (*CustomerSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerSummary) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CustomerSummary) GetOrdersCount() int32 {
	if x != nil {
		return x.OrdersCount
	}
	return 0
}

func (x *CustomerSummary) GetLifetimeValueCents() int64 {
	if x != nil {
		return x.LifetimeValueCents
	}
	return 0
}

func (x *CustomerSummary) GetAverageOrderValueCents() int64 {
	if x != nil {
		return x.AverageOrderValueCents
	}
	return 0
}

func (x *CustomerSummary) GetFavoriteCategory() string {
	if x != nil {
		return x.FavoriteCategory
	}
	return ""
}

func (x *CustomerSummary) GetLastOrderAt() string {
	if x != nil {
		return x.LastOrderAt
	}
	return ""
}

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku            string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	PriceCents     int32                  `protobuf:"varint,5,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	InventoryCount int32                  `protobuf:"varint,6,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_proto_loadtest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sku            string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category       string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	PriceCents     int32                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	InventoryCount int32                  `protobuf:"varint,5,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *CreateProductRequest) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku            string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Quantity       int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int32                  `protobuf:"varint,6,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	LineTotalCents int32                  `protobuf:"varint,7,opt,name=line_total_cents,json=lineTotalCents,proto3" json:"line_total_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_proto_loadtest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{6}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceCents() int32 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderItem) GetLineTotalCents() int32 {
	if x != nil {
		return x.LineTotalCents
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer      *Customer              `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalCents    int32                  `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	Items         []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_loadtest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{7}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalCents() int32 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_api_proto_loadtest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{8}
}

func (x *OrderItemInput) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItemInput) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Items         []*OrderItemInput      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SearchOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	MinTotalCents  int64                  `protobuf:"varint,3,opt,name=min_total_cents,json=minTotalCents,proto3" json:"min_total_cents,omitempty"`
	CreatedFrom    string                 `protobuf:"bytes,4,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`          // RFC3339
	CreatedThrough string                 `protobuf:"bytes,5,opt,name=created_through,json=createdThrough,proto3" json:"created_through,omitempty"` // RFC3339
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchOrdersRequest) Reset() {
	*x = SearchOrdersRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersRequest) ProtoMessage() {}

func (x *SearchOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersRequest.ProtoReflect.Descriptor instead.
func (*SearchOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{11}
}

func (x *SearchOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SearchOrdersRequest) GetMinTotalCents() int64 {
	if x != nil {
		return x.MinTotalCents
	}
	return 0
}

func (x *SearchOrdersRequest) GetCreatedFrom() string {
	if x != nil {
		return x.CreatedFrom
	}
	return ""
}

func (x *SearchOrdersRequest) GetCreatedThrough() string {
	if x != nil {
		return x.CreatedThrough
	}
	return ""
}

func (x *SearchOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type OrderSearchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId       string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName     string                 `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalCents       int32                  `protobuf:"varint,5,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	TotalItems       int32                  `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	DistinctProducts int32                  `protobuf:"varint,8,opt,name=distinct_products,json=distinctProducts,proto3" json:"distinct_products,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderSearchResult) Reset() {
	*x = OrderSearchResult{}
	mi := &file_api_proto_loadtest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSearchResult) ProtoMessage() {}

func (x *OrderSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSearchResult.ProtoReflect.Descriptor instead.
func (*OrderSearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{12}
}

func (x *OrderSearchResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderSearchResult) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderSearchResult) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *OrderSearchResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderSearchResult) GetTotalCents() int32 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *OrderSearchResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderSearchResult) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *OrderSearchResult) GetDistinctProducts() int32 {
	if x != nil {
		return x.DistinctProducts
	}
	return 0
}

type SearchOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*OrderSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersResponse) Reset() {
	*x = SearchOrdersResponse{}
	mi := &file_api_proto_loadtest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersResponse) ProtoMessage() {}

func (x *SearchOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersResponse.ProtoReflect.Descriptor instead.
func (*SearchOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{13}
}

func (x *SearchOrdersResponse) GetResults() []*OrderSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TopProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProductsRequest) Reset() {
	*x = TopProductsRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProductsRequest) ProtoMessage() {}

func (x *TopProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProductsRequest.ProtoReflect.Descriptor instead.
func (*TopProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{14}
}

func (x *TopProductsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *TopProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	UnitsSold     int32                  `protobuf:"varint,5,opt,name=units_sold,json=unitsSold,proto3" json:"units_sold,omitempty"`
	RevenueCents  int64                  `protobuf:"varint,6,opt,name=revenue_cents,json=revenueCents,proto3" json:"revenue_cents,omitempty"`
	OrdersCount   int32                  `protobuf:"varint,7,opt,name=orders_count,json=ordersCount,proto3" json:"orders_count,omitempty"`
	RevenueRank   int32                  `protobuf:"varint,8,opt,name=revenue_rank,json=revenueRank,proto3" json:"revenue_rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProduct) Reset() {
	*x = TopProduct{}
	mi := &file_api_proto_loadtest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProduct) ProtoMessage() {}

func (x *TopProduct) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProduct.ProtoReflect.Descriptor instead.
func (*TopProduct) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{15}
}

func (x *TopProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TopProduct) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *TopProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopProduct) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TopProduct) GetUnitsSold() int32 {
	if x != nil {
		return x.UnitsSold
	}
	return 0
}

func (x *TopProduct) GetRevenueCents() int64 {
	if x != nil {
		return x.RevenueCents
	}
	return 0
}

func (x *TopProduct) GetOrdersCount() int32 {
	if x != nil {
		return x.OrdersCount
	}
	return 0
}

func (x *TopProduct) GetRevenueRank() int32 {
	if x != nil {
		return x.RevenueRank
	}
	return 0
}

type TopProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*TopProduct          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProductsResponse) Reset() {
	*x = TopProductsResponse{}
	mi := &file_api_proto_loadtest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProductsResponse) ProtoMessage() {}

func (x *TopProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProductsResponse.ProtoReflect.Descriptor instead.
func (*TopProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{16}
}

func (x *TopProductsResponse) GetProducts() []*TopProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type LargePayloadRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	PayloadSizeBytes int64                  `protobuf:"varint,4,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"`
	Sha256           string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LargePayloadRecord) Reset() {
	*x = LargePayloadRecord{}
	mi := &file_api_proto_loadtest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargePayloadRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargePayloadRecord) ProtoMessage() {}

func (x *LargePayloadRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargePayloadRecord.ProtoReflect.Descriptor instead.
func (*LargePayloadRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{17}
}

func (x *LargePayloadRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LargePayloadRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LargePayloadRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *LargePayloadRecord) GetPayloadSizeBytes() int64 {
	if x != nil {
		return x.PayloadSizeBytes
	}
	return 0
}

func (x *LargePayloadRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *LargePayloadRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LargePayloadDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *LargePayloadRecord    `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargePayloadDetail) Reset() {
	*x = LargePayloadDetail{}
	mi := &file_api_proto_loadtest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargePayloadDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargePayloadDetail) ProtoMessage() {}

func (x *LargePayloadDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargePayloadDetail.ProtoReflect.Descriptor instead.
func (*LargePayloadDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{18}
}

func (x *LargePayloadDetail) GetRecord() *LargePayloadRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *LargePayloadDetail) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateLargePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLargePayloadRequest) Reset() {
	*x = CreateLargePayloadRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLargePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLargePayloadRequest) ProtoMessage() {}

func (x *CreateLargePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLargePayloadRequest.ProtoReflect.Descriptor instead.
func (*CreateLargePayloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{19}
}

func (x *CreateLargePayloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLargePayloadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateLargePayloadRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GetLargePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadId     string                 `protobuf:"bytes,1,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLargePayloadRequest) Reset() {
	*x = GetLargePayloadRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLargePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLargePayloadRequest) ProtoMessage() {}

func (x *GetLargePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLargePayloadRequest.ProtoReflect.Descriptor instead.
func (*GetLargePayloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{20}
}

func (x *GetLargePayloadRequest) GetPayloadId() string {
	if x != nil {
		return x.PayloadId
	}
	return ""
}

type DeleteLargePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadId     string                 `protobuf:"bytes,1,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLargePayloadRequest) Reset() {
	*x = DeleteLargePayloadRequest{}
	mi := &file_api_proto_loadtest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLargePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLargePayloadRequest) ProtoMessage() {}

func (x *DeleteLargePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLargePayloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteLargePayloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteLargePayloadRequest) GetPayloadId() string {
	if x != nil {
		return x.PayloadId
	}
	return ""
}

type DeleteLargePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Record        *LargePayloadRecord    `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLargePayloadResponse) Reset() {
	*x = DeleteLargePayloadResponse{}
	mi := &file_api_proto_loadtest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLargePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLargePayloadResponse) ProtoMessage() {}

func (x *DeleteLargePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_loadtest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLargePayloadResponse.ProtoReflect.Descriptor instead.
func (*DeleteLargePayloadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_loadtest_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteLargePayloadResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteLargePayloadResponse) GetRecord() *LargePayloadRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_api_proto_loadtest_proto protoreflect.FileDescriptor

const file_api_proto_loadtest_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/loadtest.proto\x12\vloadtest.v1\"\x86\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x18\n" +
	"\asegment\x18\x04 \x01(\tR\asegment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"d\n" +
	"\x15CreateCustomerRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\"<\n" +
	"\x19GetCustomerSummaryRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"\xa5\x02\n" +
	"\x0fCustomerSummary\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.loadtest.v1.CustomerR\bcustomer\x12!\n" +
	"\forders_count\x18\x02 \x01(\x05R\vordersCount\x120\n" +
	"\x14lifetime_value_cents\x18\x03 \x01(\x03R\x12lifetimeValueCents\x129\n" +
	"\x19average_order_value_cents\x18\x04 \x01(\x03R\x16averageOrderValueCents\x12+\n" +
	"\x11favorite_category\x18\x05 \x01(\tR\x10favoriteCategory\x12\"\n" +
	"\rlast_order_at\x18\x06 \x01(\tR\vlastOrderAt\"\xc4\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1f\n" +
	"\vprice_cents\x18\x05 \x01(\x05R\n" +
	"priceCents\x12'\n" +
	"\x0finventory_count\x18\x06 \x01(\x05R\x0einventoryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xa2\x01\n" +
	"\x14CreateProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x05R\n" +
	"priceCents\x12'\n" +
	"\x0finventory_count\x18\x05 \x01(\x05R\x0einventoryCount\"\xdc\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x06 \x01(\x05R\x0eunitPriceCents\x12(\n" +
	"\x10line_total_cents\x18\a \x01(\x05R\x0elineTotalCents\"\xd0\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\bcustomer\x18\x02 \x01(\v2\x15.loadtest.v1.CustomerR\bcustomer\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_cents\x18\x04 \x01(\x05R\n" +
	"totalCents\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12,\n" +
	"\x05items\x18\x06 \x03(\v2\x16.loadtest.v1.OrderItemR\x05items\"K\n" +
	"\x0eOrderItemInput\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x80\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x05items\x18\x03 \x03(\v2\x1b.loadtest.v1.OrderItemInputR\x05items\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xf0\x01\n" +
	"\x13SearchOrdersRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12&\n" +
	"\x0fmin_total_cents\x18\x03 \x01(\x03R\rminTotalCents\x12!\n" +
	"\fcreated_from\x18\x04 \x01(\tR\vcreatedFrom\x12'\n" +
	"\x0fcreated_through\x18\x05 \x01(\tR\x0ecreatedThrough\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"\x9a\x02\n" +
	"\x11OrderSearchResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x03 \x01(\tR\fcustomerName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_cents\x18\x05 \x01(\x05R\n" +
	"totalCents\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x05R\n" +
	"totalItems\x12+\n" +
	"\x11distinct_products\x18\b \x01(\x05R\x10distinctProducts\"P\n" +
	"\x14SearchOrdersResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.loadtest.v1.OrderSearchResultR\aresults\">\n" +
	"\x12TopProductsRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xf7\x01\n" +
	"\n" +
	"TopProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"units_sold\x18\x05 \x01(\x05R\tunitsSold\x12#\n" +
	"\rrevenue_cents\x18\x06 \x01(\x03R\frevenueCents\x12!\n" +
	"\forders_count\x18\a \x01(\x05R\vordersCount\x12!\n" +
	"\frevenue_rank\x18\b \x01(\x05R\vrevenueRank\"J\n" +
	"\x13TopProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.loadtest.v1.TopProductR\bproducts\"\xc0\x01\n" +
	"\x12LargePayloadRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12,\n" +
	"\x12payload_size_bytes\x18\x04 \x01(\x03R\x10payloadSizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"g\n" +
	"\x12LargePayloadDetail\x127\n" +
	"\x06record\x18\x01 \x01(\v2\x1f.loadtest.v1.LargePayloadRecordR\x06record\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"l\n" +
	"\x19CreateLargePayloadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"7\n" +
	"\x16GetLargePayloadRequest\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x01 \x01(\tR\tpayloadId\":\n" +
	"\x19DeleteLargePayloadRequest\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x01 \x01(\tR\tpayloadId\"o\n" +
	"\x1aDeleteLargePayloadResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x127\n" +
	"\x06record\x18\x02 \x01(\v2\x1f.loadtest.v1.LargePayloadRecordR\x06record2\xcc\x06\n" +
	"\x0fLoadTestService\x12K\n" +
	"\x0eCreateCustomer\x12\".loadtest.v1.CreateCustomerRequest\x1a\x15.loadtest.v1.Customer\x12Z\n" +
	"\x12GetCustomerSummary\x12&.loadtest.v1.GetCustomerSummaryRequest\x1a\x1c.loadtest.v1.CustomerSummary\x12H\n" +
	"\rCreateProduct\x12!.loadtest.v1.CreateProductRequest\x1a\x14.loadtest.v1.Product\x12B\n" +
	"\vCreateOrder\x12\x1f.loadtest.v1.CreateOrderRequest\x1a\x12.loadtest.v1.Order\x12<\n" +
	"\bGetOrder\x12\x1c.loadtest.v1.GetOrderRequest\x1a\x12.loadtest.v1.Order\x12S\n" +
	"\fSearchOrders\x12 .loadtest.v1.SearchOrdersRequest\x1a!.loadtest.v1.SearchOrdersResponse\x12P\n" +
	"\vTopProducts\x12\x1f.loadtest.v1.TopProductsRequest\x1a .loadtest.v1.TopProductsResponse\x12]\n" +
	"\x12CreateLargePayload\x12&.loadtest.v1.CreateLargePayloadRequest\x1a\x1f.loadtest.v1.LargePayloadRecord\x12W\n" +
	"\x0fGetLargePayload\x12#.loadtest.v1.GetLargePayloadRequest\x1a\x1f.loadtest.v1.LargePayloadDetail\x12e\n" +
	"\x12DeleteLargePayload\x12&.loadtest.v1.DeleteLargePayloadRequest\x1a'.loadtest.v1.DeleteLargePayloadResponseB&Z$loadtestgrpcapi/api/proto/loadtestv1b\x06proto3"

var (
	file_api_proto_loadtest_proto_rawDescOnce sync.Once
	file_api_proto_loadtest_proto_rawDescData []byte
)

func file_api_proto_loadtest_proto_rawDescGZIP() []byte {
	file_api_proto_loadtest_proto_rawDescOnce.Do(func() {
		file_api_proto_loadtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_loadtest_proto_rawDesc), len(file_api_proto_loadtest_proto_rawDesc)))
	})
	return file_api_proto_loadtest_proto_rawDescData
}

var file_api_proto_loadtest_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_loadtest_proto_goTypes = []any{
	(*Customer)(nil),                   // 0: loadtest.v1.Customer
	(*CreateCustomerRequest)(nil),      // 1: loadtest.v1.CreateCustomerRequest
	(*GetCustomerSummaryRequest)(nil),  // 2: loadtest.v1.GetCustomerSummaryRequest
	(*CustomerSummary)(nil),            // 3: loadtest.v1.CustomerSummary
	(*Product)(nil),                    // 4: loadtest.v1.Product
	(*CreateProductRequest)(nil),       // 5: loadtest.v1.CreateProductRequest
	(*OrderItem)(nil),                  // 6: loadtest.v1.OrderItem
	(*Order)(nil),                      // 7: loadtest.v1.Order
	(*OrderItemInput)(nil),             // 8: loadtest.v1.OrderItemInput
	(*CreateOrderRequest)(nil),         // 9: loadtest.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),            // 10: loadtest.v1.GetOrderRequest
	(*SearchOrdersRequest)(nil),        // 11: loadtest.v1.SearchOrdersRequest
	(*OrderSearchResult)(nil),          // 12: loadtest.v1.OrderSearchResult
	(*SearchOrdersResponse)(nil),       // 13: loadtest.v1.SearchOrdersResponse
	(*TopProductsRequest)(nil),         // 14: loadtest.v1.TopProductsRequest
	(*TopProduct)(nil),                 // 15: loadtest.v1.TopProduct
	(*TopProductsResponse)(nil),        // 16: loadtest.v1.TopProductsResponse
	(*LargePayloadRecord)(nil),         // 17: loadtest.v1.LargePayloadRecord
	(*LargePayloadDetail)(nil),         // 18: loadtest.v1.LargePayloadDetail
	(*CreateLargePayloadRequest)(nil),  // 19: loadtest.v1.CreateLargePayloadRequest
	(*GetLargePayloadRequest)(nil),     // 20: loadtest.v1.GetLargePayloadRequest
	(*DeleteLargePayloadRequest)(nil),  // 21: loadtest.v1.DeleteLargePayloadRequest
	(*DeleteLargePayloadResponse)(nil), // 22: loadtest.v1.DeleteLargePayloadResponse
}
var file_api_proto_loadtest_proto_depIdxs = []int32{
	0,  // 0: loadtest.v1.CustomerSummary.customer:type_name -> loadtest.v1.Customer
	0,  // 1: loadtest.v1.Order.customer:type_name -> loadtest.v1.Customer
	6,  // 2: loadtest.v1.Order.items:type_name -> loadtest.v1.OrderItem
	8,  // 3: loadtest.v1.CreateOrderRequest.items:type_name -> loadtest.v1.OrderItemInput
	12, // 4: loadtest.v1.SearchOrdersResponse.results:type_name -> loadtest.v1.OrderSearchResult
	15, // 5: loadtest.v1.TopProductsResponse.products:type_name -> loadtest.v1.TopProduct
	17, // 6: loadtest.v1.LargePayloadDetail.record:type_name -> loadtest.v1.LargePayloadRecord
	17, // 7: loadtest.v1.DeleteLargePayloadResponse.record:type_name -> loadtest.v1.LargePayloadRecord
	1,  // 8: loadtest.v1.LoadTestService.CreateCustomer:input_type -> loadtest.v1.CreateCustomerRequest
	2,  // 9: loadtest.v1.LoadTestService.GetCustomerSummary:input_type -> loadtest.v1.GetCustomerSummaryRequest
	5,  // 10: loadtest.v1.LoadTestService.CreateProduct:input_type -> loadtest.v1.CreateProductRequest
	9,  // 11: loadtest.v1.LoadTestService.CreateOrder:input_type -> loadtest.v1.CreateOrderRequest
	10, // 12: loadtest.v1.LoadTestService.GetOrder:input_type -> loadtest.v1.GetOrderRequest
	11, // 13: loadtest.v1.LoadTestService.SearchOrders:input_type -> loadtest.v1.SearchOrdersRequest
	14, // 14: loadtest.v1.LoadTestService.TopProducts:input_type -> loadtest.v1.TopProductsRequest
	19, // 15: loadtest.v1.LoadTestService.CreateLargePayload:input_type -> loadtest.v1.CreateLargePayloadRequest
	20, // 16: loadtest.v1.LoadTestService.GetLargePayload:input_type -> loadtest.v1.GetLargePayloadRequest
	21, // 17: loadtest.v1.LoadTestService.DeleteLargePayload:input_type -> loadtest.v1.DeleteLargePayloadRequest
	0,  // 18: loadtest.v1.LoadTestService.CreateCustomer:output_type -> loadtest.v1.Customer
	3,  // 19: loadtest.v1.LoadTestService.GetCustomerSummary:output_type -> loadtest.v1.CustomerSummary
	4,  // 20: loadtest.v1.LoadTestService.CreateProduct:output_type -> loadtest.v1.Product
	7,  // 21: loadtest.v1.LoadTestService.CreateOrder:output_type -> loadtest.v1.Order
	7,  // 22: loadtest.v1.LoadTestService.GetOrder:output_type -> loadtest.v1.Order
	13, // 23: loadtest.v1.LoadTestService.SearchOrders:output_type -> loadtest.v1.SearchOrdersResponse
	16, // 24: loadtest.v1.LoadTestService.TopProducts:output_type -> loadtest.v1.TopProductsResponse
	17, // 25: loadtest.v1.LoadTestService.CreateLargePayload:output_type -> loadtest.v1.LargePayloadRecord
	18, // 26: loadtest.v1.LoadTestService.GetLargePayload:output_type -> loadtest.v1.LargePayloadDetail
	22, // 27: loadtest.v1.LoadTestService.DeleteLargePayload:output_type -> loadtest.v1.DeleteLargePayloadResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_loadtest_proto_init() }
func file_api_proto_loadtest_proto_init() {
	if File_api_proto_loadtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_loadtest_proto_rawDesc), len(file_api_proto_loadtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_loadtest_proto_goTypes,
		DependencyIndexes: file_api_proto_loadtest_proto_depIdxs,
		MessageInfos:      file_api_proto_loadtest_proto_msgTypes,
	}.Build()
	File_api_proto_loadtest_proto = out.File
	file_api_proto_loadtest_proto_goTypes = nil
	file_api_proto_loadtest_proto_depIdxs = nil
}
