// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: api/proto/loadtest.proto

package loadtestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadTestService_CreateCustomer_FullMethodName     = "/loadtest.v1.LoadTestService/CreateCustomer"
	LoadTestService_GetCustomerSummary_FullMethodName = "/loadtest.v1.LoadTestService/GetCustomerSummary"
	LoadTestService_CreateProduct_FullMethodName      = "/loadtest.v1.LoadTestService/CreateProduct"
	LoadTestService_CreateOrder_FullMethodName        = "/loadtest.v1.LoadTestService/CreateOrder"
	LoadTestService_GetOrder_FullMethodName           = "/loadtest.v1.LoadTestService/GetOrder"
	LoadTestService_SearchOrders_FullMethodName       = "/loadtest.v1.LoadTestService/SearchOrders"
	LoadTestService_TopProducts_FullMethodName        = "/loadtest.v1.LoadTestService/TopProducts"
	LoadTestService_CreateLargePayload_FullMethodName = "/loadtest.v1.LoadTestService/CreateLargePayload"
	LoadTestService_GetLargePayload_FullMethodName    = "/loadtest.v1.LoadTestService/GetLargePayload"
	LoadTestService_DeleteLargePayload_FullMethodName = "/loadtest.v1.LoadTestService/DeleteLargePayload"
)

// LoadTestServiceClient is the client API for LoadTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LoadTestService exposes CRUD operations for the gRPC memory load test.
type LoadTestServiceClient interface {
	// Customer operations
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*Customer, error)
	GetCustomerSummary(ctx context.Context, in *GetCustomerSummaryRequest, opts ...grpc.CallOption) (*CustomerSummary, error)
	// Product operations
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	// Order operations
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*SearchOrdersResponse, error)
	// Analytics
	TopProducts(ctx context.Context, in *TopProductsRequest, opts ...grpc.CallOption) (*TopProductsResponse, error)
	// Large payload operations
	CreateLargePayload(ctx context.Context, in *CreateLargePayloadRequest, opts ...grpc.CallOption) (*LargePayloadRecord, error)
	GetLargePayload(ctx context.Context, in *GetLargePayloadRequest, opts ...grpc.CallOption) (*LargePayloadDetail, error)
	DeleteLargePayload(ctx context.Context, in *DeleteLargePayloadRequest, opts ...grpc.CallOption) (*DeleteLargePayloadResponse, error)
}

type loadTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadTestServiceClient(cc grpc.ClientConnInterface) LoadTestServiceClient {
	return &loadTestServiceClient{cc}
}

func (c *loadTestServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*Customer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Customer)
	err := c.cc.Invoke(ctx, LoadTestService_CreateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) GetCustomerSummary(ctx context.Context, in *GetCustomerSummaryRequest, opts ...grpc.CallOption) (*CustomerSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerSummary)
	err := c.cc.Invoke(ctx, LoadTestService_GetCustomerSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Product)
	err := c.cc.Invoke(ctx, LoadTestService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, LoadTestService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, LoadTestService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) SearchOrders(ctx context.Context, in *SearchOrdersRequest, opts ...grpc.CallOption) (*SearchOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchOrdersResponse)
	err := c.cc.Invoke(ctx, LoadTestService_SearchOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) TopProducts(ctx context.Context, in *TopProductsRequest, opts ...grpc.CallOption) (*TopProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopProductsResponse)
	err := c.cc.Invoke(ctx, LoadTestService_TopProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) CreateLargePayload(ctx context.Context, in *CreateLargePayloadRequest, opts ...grpc.CallOption) (*LargePayloadRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LargePayloadRecord)
	err := c.cc.Invoke(ctx, LoadTestService_CreateLargePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) GetLargePayload(ctx context.Context, in *GetLargePayloadRequest, opts ...grpc.CallOption) (*LargePayloadDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LargePayloadDetail)
	err := c.cc.Invoke(ctx, LoadTestService_GetLargePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) DeleteLargePayload(ctx context.Context, in *DeleteLargePayloadRequest, opts ...grpc.CallOption) (*DeleteLargePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLargePayloadResponse)
	err := c.cc.Invoke(ctx, LoadTestService_DeleteLargePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadTestServiceServer is the server API for LoadTestService service.
// All implementations must embed UnimplementedLoadTestServiceServer
// for forward compatibility.
//
// LoadTestService exposes CRUD operations for the gRPC memory load test.
type LoadTestServiceServer interface {
	// Customer operations
	CreateCustomer(context.Context, *CreateCustomerRequest) (*Customer, error)
	GetCustomerSummary(context.Context, *GetCustomerSummaryRequest) (*CustomerSummary, error)
	// Product operations
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	// Order operations
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	SearchOrders(context.Context, *SearchOrdersRequest) (*SearchOrdersResponse, error)
	// Analytics
	TopProducts(context.Context, *TopProductsRequest) (*TopProductsResponse, error)
	// Large payload operations
	CreateLargePayload(context.Context, *CreateLargePayloadRequest) (*LargePayloadRecord, error)
	GetLargePayload(context.Context, *GetLargePayloadRequest) (*LargePayloadDetail, error)
	DeleteLargePayload(context.Context, *DeleteLargePayloadRequest) (*DeleteLargePayloadResponse, error)
	mustEmbedUnimplementedLoadTestServiceServer()
}

// UnimplementedLoadTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadTestServiceServer struct{}

func (UnimplementedLoadTestServiceServer) CreateCustomer(context.Context, *CreateCustomerRequest) (*Customer, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedLoadTestServiceServer) GetCustomerSummary(context.Context, *GetCustomerSummaryRequest) (*CustomerSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerSummary not implemented")
}
func (UnimplementedLoadTestServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*Product, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedLoadTestServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedLoadTestServiceServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedLoadTestServiceServer) SearchOrders(context.Context, *SearchOrdersRequest) (*SearchOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedLoadTestServiceServer) TopProducts(context.Context, *TopProductsRequest) (*TopProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopProducts not implemented")
}
func (UnimplementedLoadTestServiceServer) CreateLargePayload(context.Context, *CreateLargePayloadRequest) (*LargePayloadRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLargePayload not implemented")
}
func (UnimplementedLoadTestServiceServer) GetLargePayload(context.Context, *GetLargePayloadRequest) (*LargePayloadDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLargePayload not implemented")
}
func (UnimplementedLoadTestServiceServer) DeleteLargePayload(context.Context, *DeleteLargePayloadRequest) (*DeleteLargePayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLargePayload not implemented")
}
func (UnimplementedLoadTestServiceServer) mustEmbedUnimplementedLoadTestServiceServer() {}
func (UnimplementedLoadTestServiceServer) testEmbeddedByValue()                         {}

// UnsafeLoadTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadTestServiceServer will
// result in compilation errors.
type UnsafeLoadTestServiceServer interface {
	mustEmbedUnimplementedLoadTestServiceServer()
}

func RegisterLoadTestServiceServer(s grpc.ServiceRegistrar, srv LoadTestServiceServer) {
	// If the following call panics, it indicates UnimplementedLoadTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadTestService_ServiceDesc, srv)
}

func _LoadTestService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_CreateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_GetCustomerSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).GetCustomerSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_GetCustomerSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).GetCustomerSummary(ctx, req.(*GetCustomerSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_SearchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).SearchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_SearchOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).SearchOrders(ctx, req.(*SearchOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_TopProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).TopProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_TopProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).TopProducts(ctx, req.(*TopProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_CreateLargePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLargePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).CreateLargePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_CreateLargePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).CreateLargePayload(ctx, req.(*CreateLargePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_GetLargePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLargePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).GetLargePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_GetLargePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).GetLargePayload(ctx, req.(*GetLargePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_DeleteLargePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLargePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).DeleteLargePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_DeleteLargePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).DeleteLargePayload(ctx, req.(*DeleteLargePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadTestService_ServiceDesc is the grpc.ServiceDesc for LoadTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadtest.v1.LoadTestService",
	HandlerType: (*LoadTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _LoadTestService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomerSummary",
			Handler:    _LoadTestService_GetCustomerSummary_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _LoadTestService_CreateProduct_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _LoadTestService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _LoadTestService_GetOrder_Handler,
		},
		{
			MethodName: "SearchOrders",
			Handler:    _LoadTestService_SearchOrders_Handler,
		},
		{
			MethodName: "TopProducts",
			Handler:    _LoadTestService_TopProducts_Handler,
		},
		{
			MethodName: "CreateLargePayload",
			Handler:    _LoadTestService_CreateLargePayload_Handler,
		},
		{
			MethodName: "GetLargePayload",
			Handler:    _LoadTestService_GetLargePayload_Handler,
		},
		{
			MethodName: "DeleteLargePayload",
			Handler:    _LoadTestService_DeleteLargePayload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/loadtest.proto",
}
