# Aerospike CE config — clear-text on port 3000.

service {
    proto-fd-max 15000
    cluster-name aerospike-sample
}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3000
    }

    heartbeat {
        mode mesh
        address local
        port 3002
        interval 150
        timeout 10
    }

    fabric {
        address local
        port 3001
    }

    info {
        port 3003
    }
}

namespace test {
    replication-factor 1
    default-ttl 0
    storage-engine memory {
        data-size 1G
    }
}
