version: "3.9"
services:
  postgres:
    image: postgres:10.5
    container_name: postgresDb
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - babab

networks:
    babab: 
      name: babab
      external: true
