// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: risk.proto

package risk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The "golden" V1 User message structure
type UserLowRisk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserLowRisk) Reset() {
	*x = UserLowRisk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLowRisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLowRisk) ProtoMessage() {}

func (x *UserLowRisk) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLowRisk.ProtoReflect.Descriptor instead.
func (*UserLowRisk) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{0}
}

func (x *UserLowRisk) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserLowRisk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLowRisk) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLowRisk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UserMediumRisk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserMediumRisk) Reset() {
	*x = UserMediumRisk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMediumRisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMediumRisk) ProtoMessage() {}

func (x *UserMediumRisk) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMediumRisk.ProtoReflect.Descriptor instead.
func (*UserMediumRisk) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{1}
}

func (x *UserMediumRisk) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMediumRisk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMediumRisk) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMediumRisk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UserHighRiskType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserHighRiskType) Reset() {
	*x = UserHighRiskType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHighRiskType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHighRiskType) ProtoMessage() {}

func (x *UserHighRiskType) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHighRiskType.ProtoReflect.Descriptor instead.
func (*UserHighRiskType) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{2}
}

func (x *UserHighRiskType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserHighRiskType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserHighRiskType) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserHighRiskType) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UserHighRiskRemoval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email            string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RemovalRequested bool   `protobuf:"varint,4,opt,name=removal_requested,json=removalRequested,proto3" json:"removal_requested,omitempty"` // Indicates if removal has been requested
	Timestamp        int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserHighRiskRemoval) Reset() {
	*x = UserHighRiskRemoval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHighRiskRemoval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHighRiskRemoval) ProtoMessage() {}

func (x *UserHighRiskRemoval) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHighRiskRemoval.ProtoReflect.Descriptor instead.
func (*UserHighRiskRemoval) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{3}
}

func (x *UserHighRiskRemoval) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserHighRiskRemoval) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserHighRiskRemoval) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserHighRiskRemoval) GetRemovalRequested() bool {
	if x != nil {
		return x.RemovalRequested
	}
	return false
}

func (x *UserHighRiskRemoval) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{4}
}

type SimpleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_risk_proto_rawDescGZIP(), []int{5}
}

func (x *SimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_risk_proto protoreflect.FileDescriptor

var file_risk_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x69,
	0x73, 0x6b, 0x22, 0x65, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x77, 0x52, 0x69, 0x73,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x68, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x52, 0x69, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x6a, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52,
	0x69, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x9a, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52, 0x69, 0x73, 0x6b,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xf5, 0x01, 0x0a, 0x0b, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x30, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x77, 0x52,
	0x69, 0x73, 0x6b, 0x12, 0x0b, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x11, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x77, 0x52,
	0x69, 0x73, 0x6b, 0x12, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65,
	0x64, 0x69, 0x75, 0x6d, 0x52, 0x69, 0x73, 0x6b, 0x12, 0x0b, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x52, 0x69, 0x73, 0x6b, 0x12, 0x3a, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x16, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52,
	0x69, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61,
	0x6c, 0x12, 0x0b, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19,
	0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x67, 0x68, 0x52, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x72, 0x69, 0x73, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_risk_proto_rawDescOnce sync.Once
	file_risk_proto_rawDescData = file_risk_proto_rawDesc
)

func file_risk_proto_rawDescGZIP() []byte {
	file_risk_proto_rawDescOnce.Do(func() {
		file_risk_proto_rawDescData = protoimpl.X.CompressGZIP(file_risk_proto_rawDescData)
	})
	return file_risk_proto_rawDescData
}

var file_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_risk_proto_goTypes = []interface{}{
	(*UserLowRisk)(nil),         // 0: risk.UserLowRisk
	(*UserMediumRisk)(nil),      // 1: risk.UserMediumRisk
	(*UserHighRiskType)(nil),    // 2: risk.UserHighRiskType
	(*UserHighRiskRemoval)(nil), // 3: risk.UserHighRiskRemoval
	(*Empty)(nil),               // 4: risk.Empty
	(*SimpleResponse)(nil),      // 5: risk.SimpleResponse
}
var file_risk_proto_depIdxs = []int32{
	4, // 0: risk.RiskService.GetUserLowRisk:input_type -> risk.Empty
	4, // 1: risk.RiskService.GetUserMediumRisk:input_type -> risk.Empty
	4, // 2: risk.RiskService.GetUserHighRiskType:input_type -> risk.Empty
	4, // 3: risk.RiskService.GetUserHighRiskRemoval:input_type -> risk.Empty
	0, // 4: risk.RiskService.GetUserLowRisk:output_type -> risk.UserLowRisk
	1, // 5: risk.RiskService.GetUserMediumRisk:output_type -> risk.UserMediumRisk
	2, // 6: risk.RiskService.GetUserHighRiskType:output_type -> risk.UserHighRiskType
	3, // 7: risk.RiskService.GetUserHighRiskRemoval:output_type -> risk.UserHighRiskRemoval
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_risk_proto_init() }
func file_risk_proto_init() {
	if File_risk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_risk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLowRisk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMediumRisk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHighRiskType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHighRiskRemoval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_risk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_proto_goTypes,
		DependencyIndexes: file_risk_proto_depIdxs,
		MessageInfos:      file_risk_proto_msgTypes,
	}.Build()
	File_risk_proto = out.File
	file_risk_proto_rawDesc = nil
	file_risk_proto_goTypes = nil
	file_risk_proto_depIdxs = nil
}
