// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: risk.proto

package risk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskServiceClient interface {
	GetUserLowRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	GetUserMediumRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	GetUserHighRiskType(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	GetUserHighRiskRemoval(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	StatusChangeHighRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) GetUserLowRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/risk.RiskService/GetUserLowRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetUserMediumRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/risk.RiskService/GetUserMediumRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetUserHighRiskType(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/risk.RiskService/GetUserHighRiskType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetUserHighRiskRemoval(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/risk.RiskService/GetUserHighRiskRemoval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) StatusChangeHighRisk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/risk.RiskService/StatusChangeHighRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility
type RiskServiceServer interface {
	GetUserLowRisk(context.Context, *Empty) (*User, error)
	GetUserMediumRisk(context.Context, *Empty) (*User, error)
	GetUserHighRiskType(context.Context, *Empty) (*User, error)
	GetUserHighRiskRemoval(context.Context, *Empty) (*User, error)
	StatusChangeHighRisk(context.Context, *Empty) (*SimpleResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRiskServiceServer struct {
}

func (UnimplementedRiskServiceServer) GetUserLowRisk(context.Context, *Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLowRisk not implemented")
}
func (UnimplementedRiskServiceServer) GetUserMediumRisk(context.Context, *Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMediumRisk not implemented")
}
func (UnimplementedRiskServiceServer) GetUserHighRiskType(context.Context, *Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserHighRiskType not implemented")
}
func (UnimplementedRiskServiceServer) GetUserHighRiskRemoval(context.Context, *Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserHighRiskRemoval not implemented")
}
func (UnimplementedRiskServiceServer) StatusChangeHighRisk(context.Context, *Empty) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusChangeHighRisk not implemented")
}
func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_GetUserLowRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetUserLowRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RiskService/GetUserLowRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetUserLowRisk(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetUserMediumRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetUserMediumRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RiskService/GetUserMediumRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetUserMediumRisk(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetUserHighRiskType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetUserHighRiskType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RiskService/GetUserHighRiskType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetUserHighRiskType(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetUserHighRiskRemoval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetUserHighRiskRemoval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RiskService/GetUserHighRiskRemoval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetUserHighRiskRemoval(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_StatusChangeHighRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).StatusChangeHighRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.RiskService/StatusChangeHighRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).StatusChangeHighRisk(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserLowRisk",
			Handler:    _RiskService_GetUserLowRisk_Handler,
		},
		{
			MethodName: "GetUserMediumRisk",
			Handler:    _RiskService_GetUserMediumRisk_Handler,
		},
		{
			MethodName: "GetUserHighRiskType",
			Handler:    _RiskService_GetUserHighRiskType_Handler,
		},
		{
			MethodName: "GetUserHighRiskRemoval",
			Handler:    _RiskService_GetUserHighRiskRemoval_Handler,
		},
		{
			MethodName: "StatusChangeHighRisk",
			Handler:    _RiskService_StatusChangeHighRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk.proto",
}
