name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working-directory:
          - book-store-inventory
          - connect-tunnel
          - dns-dedup
          - dns-mock-test
          - echo-mysql
          - echo-sql
          - fasthttp-postgres
          - gin-mongo
          - gin-redis
          - go-dedup
          - go-docker-timefreeze
          - go-grpc
          - go-jwt
          - go-memory-load
          - go-redis
          - go-twilio
          - graphql-sql
          - grpc-mongo
          - grpc-secret
          - http-pokeapi
          - http-postgres
          - http-sse
          - mux-elasticsearch
          - mux-mysql
          - mux-sql
          - proxy-stress-test
          - risk-profile
          - S3-Keploy
          - simple-grpc
          - sqs-samples
          - sse-preflight
          - sse-redis
          - sse-svelte
          - tls-dadjoke
          - users-profile

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.63.4

          # Optional: working directory, useful for monorepos
          working-directory: ${{matrix.working-directory}}

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          install-mode: "goinstall"
