name: GolangCI-Lint (PR Changes Only)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  golangci-lint:
    name: GolangCI Lint Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Run golangci-lint on Changed Files
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          only-new-issues: true
          args: --timeout=5m
